# docker-compose.yml for Lab Automation
# to build the images:  docker-compose build
# to build start everything: docker-compose up --build
# to build start everything after code change: docker-compose up --build

#networks:
  #container_network

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: platform_status
      POSTGRES_PASSWORD: platform_status
      POSTGRES_DB: platform_status_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    network_mode: host

  platform_status_db:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/platform_status_db
    environment:
      DJANGO_SETTINGS_MODULE: settings
    volumes:
        - ./status_db/settings.py:/opt/platform_status_db/settings.py
    depends_on:
      - database

  wipe_db:
    image: continuumio/miniconda3
    depends_on:
      - platform_status_db
    volumes:
        - .:/opt/adaptation_template/
        - platform_status:/opt/platform_status_db
    command: >
      bash -c "conda install python=3.11 &&
      pip install -e /opt/platform_status_db &&
      pip install -r /opt/adaptation_template/requirements.txt &&
      cd /opt/adaptation_template/ &&
      echo 'Wiping the database and adding lab setup...' &&
      python scripts/add_lab_setup_to_db.py"
    network_mode: host
    environment:
      - "LAB_STATUS_DB_PATH=/opt/platform_status_db/platform_status_db/db.sqlite3"

  labscheduler:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/lab-scheduler/labscheduler
    network_mode: host
    volumes:
      - ./:/opt/adaptation_template/
    command: >
      labscheduler --lab-config-path /opt/adaptation_template/lab_adaption/platform_config.yaml

  laborchestrator:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/laborchestrator
    network_mode: host
    volumes:
      - ./lab_adaption:/opt/adaptation_template/lab_adaption
      - platform_status:/opt/platform_status_db
    working_dir: /opt/adaptation_template/
    command: >
      bash -c "pip install -e  /opt/platform_status_db &&
      python -m lab_adaption.start_script"
    environment:
      - "LAB_STATUS_DB_PATH=/opt/platform_status_db/platform_status_db/db.sqlite3"
#    depends_on:
#      wipe_db:
#        condition: service_completed_successfully

  sila_servers:
    image: continuumio/miniconda3
    depends_on:
      - labscheduler
    volumes:
      - .:/opt/adaptation_template/
    command: >
      bash -c "conda install -y python=3.11 &&
      pip install --no-input -e /opt/adaptation_template/ &&
      pip install --no-input -r /opt/adaptation_template/requirements_servers.txt &&
      cd /opt/adaptation_template/lab_adaption/ &&
      echo 'Starting Sila servers...' &&
      start_sila_servers"
    network_mode: host

volumes:
  platform_status:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/dsmits/projects/osla/platform_status_db/
