# docker-compose.yml for Lab Automation
# to build the images:  docker-compose build
# to build start everything: docker-compose up --build
# to build start everything after code change: docker-compose up --build

#networks:
  #container_network

services:
  wipe_db:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/platform_status_db
    depends_on:
      - platform_status_db
    volumes:
        - .:/opt/adaption_template/
    command: >
      bash -c "pip install -r /opt/adaption_template/requirements.txt &&
      export PYTHONPATH=/opt/adaption_template/:$PYTHONPATH &&
      echo 'Wiping the database and adding lab setup...' &&
      python /opt/adaption_template/scripts/add_lab_setup_to_db.py"
    network_mode: host
    environment:
      - DJANGO_SETTINGS_MODULE=settings

  labscheduler:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/lab-scheduler/labscheduler
    network_mode: host
    volumes:
      - ./:/opt/adaptation_template/
    command: >
      labscheduler --lab-config-path /opt/adaptation_template/lab_adaption/platform_config.yaml


  laborchestrator:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/laborchestrator
    network_mode: host
    volumes:
      - ./:/opt/adaptation_template/
    working_dir: /opt/adaptation_template/
    command: lab_adaption/start_orchestrator.sh
    environment:
      - "DJANGO_SETTINGS_MODULE=settings"
#    depends_on:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: platform_status
      POSTGRES_PASSWORD: platform_status
      POSTGRES_DB: platform_status_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U platform_status -d platform_status_db" ]
      interval: 10s
      timeout: 5s
      retries: 5


  platform_status_db:
    image: registry.gitlab.com/openlabautomation/lab-automation-packages/platform_status_db
    environment:
      DJANGO_SETTINGS_MODULE: settings
    volumes:
        - ./settings.py:/opt/platform_status_db/settings.py
    depends_on:
      database:
        condition: service_healthy

    network_mode: host
#      wipe_db:
#        condition: service_completed_successfully

  sila_servers:
    image: continuumio/miniconda3
    depends_on:
      - labscheduler
    volumes:
      - .:/opt/adaptation_template/
    command: >
      bash -c "pip install --no-input -e /opt/adaptation_template/ &&
      pip install --no-input -r /opt/adaptation_template/requirements_servers.txt &&
      cd /opt/adaptation_template/lab_adaption/ &&
      echo 'Starting Sila servers...' &&
      start_sila_servers"
    network_mode: host
