description:
    - "DSetup of a student lab in uppsala university cellar"
sila_servers:
    storage:
        Hotel1:
            capacity: 3
        Hotel2:
            capacity: 1
        #Hotel3:
        #    capacity: 7
    incubators:
        Cytomat2C:
            capacity: 42
    washer_dispensers:
        Washer:
            capacity: 1
    sealers:
        Sealer:
            capacity: 1
    movers:
        XArm:
            capacity: 1
    microscopes:
        Squid1:
            capacity: 1
        #Squid2:
        #    capacity: 1
    humans:
        Human:
            capacity: 99

# ------ Translation to used resources in the process description ------
pythonlab_translation:
    storage: LabwareStorageResource
    movers: MoverServiceResource
    incubators: IncubatorServiceResource
    humans: HumanServiceResource
    microscopes: MicroscopeServiceResource
    washer_dispensers: WasherDispenserServiceResource
    sealers: PlateSealerServiceResource
